"""Compiles Tailwind CSS at build time via the Tailwind CLI (see package.json).

Generates tailwind.config.js from engine.config.THEME_CONFIG -- the same theme
data already used to render the custom CSS block in base.html -- so there's a
single source of truth for theme colors. The CLI then scans the *rendered*
dist/**/*.html output rather than the Python/Jinja source: cards.py builds some
class names dynamically (e.g. color.replace('border-', 'bg-')), and by the time
that HTML is written to dist/, those are already literal text Tailwind's
scanner can see -- scanning the .py source directly would miss them.
"""
import os
import shutil
import subprocess

from engine.config import CURRENT_THEME, OUTPUT_DIR, ROOT_DIR


def generate_config():
    colors = CURRENT_THEME["colors"]
    color_map = {
        "aurelia-bg": colors["bg_main"],
        "aurelia-card": colors["bg_layer_1"],
        "aurelia-surface": colors["bg_layer_2"],
        "aurelia-text": colors["text_main"],
        "aurelia-muted": colors["text_muted"],
        "aurelia-inverted": colors["text_inverted"],
        "aurelia-border": colors["border_main"],
        "aurelia-primary": colors["primary"],
        "aurelia-secondary": colors["secondary"],
        "aurelia-tertiary": colors["tertiary"],
        "aurelia-accent": colors["accent"],
        # Pre-"semantic theme" names still referenced by the footer, the
        # command palette badges, and status indicators. They were never in
        # this config (so they've silently rendered with no color at all) --
        # aliased here to their nearest semantic equivalent instead of left broken.
        "aurelia-cyan": colors["primary"],
        "aurelia-orange": colors["tertiary"],
        "aurelia-green": colors["accent"],
        "aurelia-purple": colors["secondary"],
        "aurelia-dim": colors["border_main"],
        "aurelia-dark": colors["bg_main"],
    }
    color_lines = ",\n      ".join(f"'{name}': {value}" for name, value in color_map.items())

    animation = ""
    if CURRENT_THEME["name"] == "CYBER_PRIME":
        animation = "\n      animation: { 'scanline': 'scanline 8s linear infinite' },"

    config_js = f"""/* AUTO-GENERATED by engine/tailwind_build.py from engine/config.py THEME_CONFIG.
 * Do not edit by hand -- edit THEME_CONFIG and rebuild instead. */
module.exports = {{
  content: ["./dist/**/*.html"],
  theme: {{
    extend: {{
      colors: {{
      {color_lines}
      }},
      borderRadius: {{ theme: {CURRENT_THEME["rounded"]} }},
      fontFamily: {{
        sans: ['Inter', 'sans-serif'],
        mono: [{CURRENT_THEME["font_mono"]}],
      }},{animation}
    }}
  }}
}}
"""
    config_path = os.path.join(ROOT_DIR, "tailwind.config.js")
    with open(config_path, "w", encoding="utf-8") as f:
        f.write(config_js)
    return config_path


def compile_css():
    """Runs the Tailwind CLI, overwriting dist/assets/css/main.css (previously
    just a passthrough copy) with the real compiled, minified stylesheet."""
    print("\n🎨 COMPILING TAILWIND CSS...")
    generate_config()

    npx = shutil.which("npx") or shutil.which("npx.cmd")
    if not npx:
        raise RuntimeError(
            "npx not found on PATH. Install Node.js, then run `npm install` in "
            "the project root before building (see package.json)."
        )

    input_css = os.path.join(ROOT_DIR, "assets", "css", "main.css")
    output_css = os.path.join(OUTPUT_DIR, "assets", "css", "main.css")

    result = subprocess.run(
        [npx, "tailwindcss", "-i", input_css, "-o", output_css, "--minify"],
        cwd=ROOT_DIR, capture_output=True, text=True,
    )
    if result.returncode != 0:
        print(result.stdout)
        print(result.stderr)
        raise RuntimeError("Tailwind CLI build failed (see output above).")

    print("   + Tailwind CSS compiled.")
