"""Compiles Tailwind CSS at build time via the Tailwind CLI (see package.json).

Generates tailwind.config.js wiring each aurelia-* utility class to a CSS
custom property (var(--aurelia-primary), not a literal hex value) -- so the
generated config itself is theme-independent. The actual per-theme values
live in dist/assets/css/theme-vars.css (see engine/theming.py), swapped at
runtime via the <html data-theme="..."> attribute. Before this split, a
theme change meant re-baking literal colors into this file and rebuilding;
now the config only has to be regenerated when the *set* of utility class
names changes, not when a theme's colors do.

The CLI scans the *rendered* dist/**/*.html output rather than the
Python/Jinja source: cards.py builds some class names dynamically (e.g.
color.replace('border-', 'bg-')), and by the time that HTML is written to
dist/, those are already literal text Tailwind's scanner can see --
scanning the .py source directly would miss them.
"""
import os
import shutil
import subprocess

from engine.config import OUTPUT_DIR, ROOT_DIR


def generate_config():
    # Every one of these compiles to `rgb(var(--aurelia-x-rgb) / <alpha>)`,
    # not a baked-in hex value -- see engine/theming.py for where
    # --aurelia-x-rgb actually gets its per-theme value. The RGB-channel
    # form (not a plain var(--aurelia-x) hex reference) is required for
    # Tailwind's /opacity modifier syntax to work at all: bg-aurelia-primary
    # /10 needs a color Tailwind can decompose into channels + an alpha
    # value, and a bare hex-string var() isn't decomposable -- Tailwind
    # would just silently skip generating that class. aurelia-cyan/dim/dark
    # are pre-"semantic theme" aliases still used by the nav dot, footer,
    # and the Garden's atmosphere overlay (border-aurelia-dim,
    # bg-aurelia-dark); aurelia-orange/green/purple were the same kind of
    # alias but ended up with zero remaining call sites once the
    # Project/Protocol pages were deleted (see CLAUDE.md "Recent history")
    # -- removed rather than kept as unused config.
    color_map = {
        "aurelia-bg": "bg-main",
        "aurelia-card": "bg-layer-1",
        "aurelia-surface": "bg-layer-2",
        "aurelia-text": "text-main",
        "aurelia-muted": "text-muted",
        "aurelia-inverted": "text-inverted",
        "aurelia-border": "border-main",
        "aurelia-primary": "primary",
        "aurelia-secondary": "secondary",
        "aurelia-tertiary": "tertiary",
        "aurelia-accent": "accent",
        "aurelia-highlight": "highlight",
        "aurelia-info": "info",
        "aurelia-insight": "insight",
        "aurelia-cyan": "primary",
        "aurelia-dim": "border-main",
        "aurelia-dark": "bg-main",
    }
    color_lines = ",\n      ".join(
        f"'{name}': 'rgb(var(--aurelia-{var}-rgb) / <alpha-value>)'" for name, var in color_map.items()
    )

    config_js = f"""/* AUTO-GENERATED by engine/tailwind_build.py.
 * Do not edit by hand -- this file no longer varies by theme (see
 * engine/theming.py for the per-theme values these classes reference). */
module.exports = {{
  content: ["./dist/**/*.html"],
  theme: {{
    extend: {{
      colors: {{
      {color_lines}
      }},
      borderRadius: {{ theme: 'var(--aurelia-radius)' }},
      fontFamily: {{
        sans: ['Inter', 'sans-serif'],
        mono: ['var(--aurelia-font-mono)', 'monospace'],
        // Headings. Defaults to the theme's own mono (the house style is
        // mono-first display type); a theme can point font_display at a
        // real display family instead -- see engine/theming.py.
        display: ['var(--aurelia-font-display)', 'monospace'],
      }},
      // Depth ladder -- shadow-e1/e2/e3 plus the inset rim highlight.
      // Values are per-theme (derived or hand-tuned); see engine/theming.py.
      boxShadow: {{
        e1: 'var(--aurelia-elevation-1)',
        e2: 'var(--aurelia-elevation-2)',
        e3: 'var(--aurelia-elevation-3)',
        rim: 'var(--aurelia-rim-light)',
        'rim-e2': 'var(--aurelia-rim-light), var(--aurelia-elevation-2)',
        'rim-e3': 'var(--aurelia-rim-light), var(--aurelia-elevation-3)',
      }},
      animation: {{ 'scanline': 'scanline 8s linear 1 forwards' }},
    }}
  }}
}}
"""
    config_path = os.path.join(ROOT_DIR, "tailwind.config.js")
    with open(config_path, "w", encoding="utf-8") as f:
        f.write(config_js)
    return config_path


def compile_css():
    """Runs the Tailwind CLI, overwriting dist/assets/css/main.css (previously
    just a passthrough copy) with the real compiled, minified stylesheet."""
    print("\n🎨 COMPILING TAILWIND CSS...")
    generate_config()

    npx = shutil.which("npx") or shutil.which("npx.cmd")
    if not npx:
        raise RuntimeError(
            "npx not found on PATH. Install Node.js, then run `npm install` in "
            "the project root before building (see package.json)."
        )

    input_css = os.path.join(ROOT_DIR, "assets", "css", "main.css")
    output_css = os.path.join(OUTPUT_DIR, "assets", "css", "main.css")

    result = subprocess.run(
        [npx, "tailwindcss", "-i", input_css, "-o", output_css, "--minify"],
        cwd=ROOT_DIR, capture_output=True, text=True,
    )
    if result.returncode != 0:
        print(result.stdout)
        print(result.stderr)
        raise RuntimeError("Tailwind CLI build failed (see output above).")

    print("   + Tailwind CSS compiled.")
