"""Generates the runtime-switchable theme stylesheet from THEME_CONFIG.

One :root[data-theme="<slug>"] block per theme, each defining the full set
of --aurelia-* custom properties, plus a bare :root block mirroring the
default theme (CURRENT_THEME) so the very first paint -- before the nav's
theme-switcher init script runs -- already has real values instead of
flashing unstyled.

Everything that used to be baked into HTML/JS at build time (a template's
{{ theme.colors.primary }}, tailwind.config.js's literal hex, even the
custom cursor's hardcoded SVG colors) now resolves through one of these
variables instead, so switching themes at runtime is a pure CSS swap --
no rebuild, and nothing left hardcoded to one theme.
"""
import os

from engine.config import CURRENT_THEME, OUTPUT_DIR, THEME_CONFIG

_COLOR_KEYS = [
    "bg_main", "bg_layer_1", "bg_layer_2",
    "text_main", "text_muted", "text_inverted",
    "border_main", "border_focus",
    "primary", "secondary", "tertiary", "accent",
]

# Optional per-theme keys and what applies when a theme omits them -- see
# THEME_CONFIG's own docstring-comment for the reasoning: a new theme only
# has to define what makes it actually different.
_DEFAULTS = {
    "font_mono": "'JetBrains Mono', monospace",
    "rounded": "2px",
    "glass_opacity": "0.6",
    "glass_border": "none",
    "glass_shadow": "none",
    "scanline_bg": "linear-gradient(0deg, rgba(0, 0, 0, 0) 0%, rgba(255, 255, 255, 0.02) 50%, rgba(0, 0, 0, 0) 100%)",
    "scanline_opacity": "0.1",
}


def theme_slug(key):
    """'CYBER_PRIME' -> 'cyber-prime'. The data-theme attribute value and
    CSS selector suffix -- used identically in Python, generated CSS, and
    the switcher's embedded JS payload so none of them can drift apart."""
    return key.lower().replace("_", "-")


def _hex_to_rgba(hex_color, alpha):
    hex_color = hex_color.lstrip("#")
    r, g, b = int(hex_color[0:2], 16), int(hex_color[2:4], 16), int(hex_color[4:6], 16)
    return f"rgba({r}, {g}, {b}, {alpha})"


def _cursor_default(colors):
    """The default arrow cursor, filled with this theme's own bg (so it
    reads as a translucent shape against a same-toned page) and outlined
    in its primary color -- previously a CYBER_PRIME-only hardcoded SVG
    that stayed cyan-on-black regardless of the active theme."""
    svg = (
        "<svg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24'>"
        f"<path d='M2 2l8.8 20.4 2.8-8.4 8.4-2.8L2 2z' fill='{colors['bg_main']}' fill-opacity='0.5' "
        f"stroke='{colors['primary']}' stroke-width='1.5' stroke-linejoin='round'/></svg>"
    ).replace("#", "%23")
    return f'url("data:image/svg+xml,{svg}"), auto'


def _cursor_interactive(colors):
    """The interactive target-reticle cursor, keyed to this theme's accent."""
    svg = (
        "<svg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24'>"
        f"<circle cx='12' cy='12' r='9' fill='none' stroke='{colors['accent']}' stroke-width='1.5'/>"
        f"<circle cx='12' cy='12' r='2' fill='{colors['accent']}'/>"
        f"<path d='M12 2v4M12 18v4M2 12h4M18 12h4' stroke='{colors['accent']}' stroke-width='1.5'/></svg>"
    ).replace("#", "%23")
    return f'url("data:image/svg+xml,{svg}") 12 12, pointer'


def _variables_for(theme):
    """Builds the {css-custom-property-name: value} map for one theme."""
    colors = theme["colors"]
    variables = {f"--aurelia-{key.replace('_', '-')}": colors[key] for key in _COLOR_KEYS}

    variables["--aurelia-font-mono"] = theme.get("font_mono", _DEFAULTS["font_mono"])
    variables["--aurelia-radius"] = theme.get("rounded", _DEFAULTS["rounded"])

    glass_opacity = theme.get("glass_opacity", _DEFAULTS["glass_opacity"])
    variables["--aurelia-glass-bg"] = _hex_to_rgba(colors["bg_main"], glass_opacity)
    variables["--aurelia-glass-border"] = theme.get("glass_border", _DEFAULTS["glass_border"])
    variables["--aurelia-glass-shadow"] = theme.get("glass_shadow", _DEFAULTS["glass_shadow"])

    variables["--aurelia-scanline-bg"] = theme.get("scanline_bg", _DEFAULTS["scanline_bg"])
    variables["--aurelia-scanline-opacity"] = theme.get("scanline_opacity", _DEFAULTS["scanline_opacity"])

    variables["--aurelia-cursor-default"] = _cursor_default(colors)
    variables["--aurelia-cursor-interactive"] = _cursor_interactive(colors)

    return variables


def _block(selector, variables):
    lines = "\n".join(f"    {name}: {value};" for name, value in variables.items())
    return f"{selector} {{\n{lines}\n}}"


def generate_theme_css():
    """Writes dist/assets/css/theme-vars.css: a bare :root block (the
    default theme, for pre-JS first paint) plus one :root[data-theme="x"]
    block per THEME_CONFIG entry. Returns the output path.
    """
    blocks = [
        "/* AUTO-GENERATED by engine/theming.py from engine/config.py THEME_CONFIG.",
        " * Do not edit by hand -- add or edit a theme there and rebuild instead. */",
        _block(":root", _variables_for(CURRENT_THEME)),
    ]
    for key, theme in THEME_CONFIG.items():
        blocks.append(_block(f':root[data-theme="{theme_slug(key)}"]', _variables_for(theme)))

    css_dir = os.path.join(OUTPUT_DIR, "assets", "css")
    os.makedirs(css_dir, exist_ok=True)
    output_path = os.path.join(css_dir, "theme-vars.css")
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n\n".join(blocks) + "\n")
    return output_path


def default_theme_slug():
    """The slug for CURRENT_THEME (config.py's default-theme selection) --
    stamped onto <html data-theme="..."> at build time so the page renders
    correctly before the switcher's init script (which may override it
    from localStorage) has run."""
    for key, theme in THEME_CONFIG.items():
        if theme is CURRENT_THEME:
            return theme_slug(key)
    return theme_slug(next(iter(THEME_CONFIG)))


def available_themes():
    """[{key, label, description, colors}, ...] for the switcher UI and its
    embedded JS payload -- 'colors' is a small swatch preview, not the full
    palette, to keep that payload light."""
    return [
        {
            "key": theme_slug(key),
            "label": theme.get("label", key.replace("_", " ").title()),
            "description": theme.get("description", ""),
            "swatch": {
                "bg": theme["colors"]["bg_main"],
                "primary": theme["colors"]["primary"],
                "secondary": theme["colors"]["secondary"],
                "accent": theme["colors"]["accent"],
            },
        }
        for key, theme in THEME_CONFIG.items()
    ]
